apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    # Storage password (PostgreSQL)
    - secretKey: storage.postgres.password.txt
      remoteRef:
        key: databases/postgresql
        property: PASSWORD
    # Session encryption key
    - secretKey: session.encryption.key
      remoteRef:
        key: cluster-infrastructure/authelia
        property: SESSION_SECRET
    # Storage encryption key
    - secretKey: storage.encryption.key
      remoteRef:
        key: cluster-infrastructure/authelia
        property: STORAGE_ENCRYPTION_KEY
    # JWT HMAC key for identity validation (password reset)
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: cluster-infrastructure/authelia
        property: JWT_HMAC_KEY
