apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-postgres-password
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-postgres-password
    creationPolicy: Owner
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: databases/postgresql-cnpg
        property: VAULT_PASSWORD
