helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-backend
    forcestring: true
  - name: image.tag
    value: latest@sha256:b8977b393526b08c6269f93d581e948cee8b014b3b29cd106db4b0a5e526cc37
    forcestring: true
