helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-backend
    forcestring: true
  - name: image.tag
    value: latest@sha256:425b0ccab9d94ac8faebd8f817d3b162c1b6a4d3ead76af7df40b1a8940d02fc
    forcestring: true
