helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-backend
    forcestring: true
  - name: image.tag
    value: latest@sha256:9cd55701c5dc4d3dc18b45fb4fd6778972d35fe1dc113be3cefdf88c63d5ac3f
    forcestring: true
