helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-frontend
    forcestring: true
  - name: image.tag
    value: latest@sha256:988e91782c6951c6e54d77b10db5dc89109ba1c0413df243be1cb9b86a678be3
    forcestring: true
