helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-frontend
    forcestring: true
  - name: image.tag
    value: latest@sha256:6e3279cb1604540392299dfebd59ef7fa57aa4878f226e6a4290c09d1d097030
    forcestring: true
