helm:
  parameters:
  - name: image.name
    value: zot0213.kro.kr/web-apps/poolc-backend
    forcestring: true
  - name: image.tag
    value: latest@sha256:71224b20488a812e42f7763d2bcc51c8dd3e2e4c7536c5a1a0409608f1ef3ec0
    forcestring: true
